trigger:
- main  # Adjust to your branch name

pool:
  vmImage: 'windows-latest'  # Use 'ubuntu-latest' for Linux builds

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install Dotnet'
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Adjust to your .NET version

# Step 2: Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore Project'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# Step 3: Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration Release'

# Step 4: Run unit tests
- task: DotNetCoreCLI@2
  displayName: 'Run Integration Tests'
  inputs:
    command: 'test'
    projects: '**/Simaira.Digital.API.Integration.csproj'
    arguments: '--configuration Release --no-build --collect:"Code Coverage"'
