# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: development
  displayName: Deploy to development
  trigger: manual
  jobs:
  - deployment: DeployJob
    environment: Dev
    strategy:
      runOnce:
       deploy:         
         steps:
         - script: echo 'hello, world Development'
           displayName: 'Run script'

- stage: Stage
  displayName: Deploy to Stage
  trigger: manual
  jobs:
  - deployment: DeployJob
    environment: Stage
    strategy:
      runOnce:
       deploy:         
         steps:
         - script: echo 'hello, world Stage'
           displayName: 'Run script'

- stage: Production
  displayName: Deploy to Production
  trigger: manual
  jobs:
  - deployment: DeployJob
    environment: Prod
    strategy:
      runOnce:
       deploy:         
         steps:
         - script: echo 'hello, world Production'
           displayName: 'Run script'
