// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Simaira.Digital.Systems.API.IntegrationTests.Features.Dishmachine
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DishMachineFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "TestSuite_Simaira.Digital",
                "DishMachine"};
        
#line 1 "DishMachine.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Dishmachine", "Dish Machine", "\tThe tests verify Dish Machine data.\r\n\tThis includes:\r\n\t1. OverallPerformance Pul" +
                    "se Check\r\n\t2. ShiftLevelPerformance", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Dish Machine")))
            {
                global::Simaira.Digital.Systems.API.IntegrationTests.Features.Dishmachine.DishMachineFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line hidden
#line 10
testRunner.Given("Get aligned CDM Sites and Accounts for \'ecolab3dcorptest1@mailinator.com\' from CD" +
                    "M API for Dish Machine", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "AccountNumber"});
#line 11
 testRunner.And("Set User Accounts", ((string)(null)), table2, "And ");
#line hidden
#line 13
 testRunner.And("Set Service Areas and Devices for Accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "AccountNumber"});
#line 14
 testRunner.And("Set Account Info", ((string)(null)), table3, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Simaira.Digital_API Get Dish Machine Overall Performance Pulse Check")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Dish Machine")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TestSuite_Simaira.Digital")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DishMachine")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DishMachineOverallPerformancePulseCheck")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integrationtest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Simaira.DigitalIntegrationtest")]
        public void Simaira_Digital_APIGetDishMachineOverallPerformancePulseCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "DishMachineOverallPerformancePulseCheck",
                    "Integrationtest",
                    "Simaira.DigitalIntegrationtest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Simaira.Digital_API Get Dish Machine Overall Performance Pulse Check", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
this.FeatureBackground();
#line hidden
#line 22
 testRunner.Given("Dish Machine Overall Performance Request Payload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
 testRunner.Then("Get Dish Machine Overall Performance for Pulse Check \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Simaira.Digital_API Get Dish Machine Overall Performance For All CDMSite Location" +
            "s")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Dish Machine")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TestSuite_Simaira.Digital")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DishMachine")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DishMachineOverallPerformanceForAllLocation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integrationtest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Simaira.DigitalIntegrationtest")]
        public void Simaira_Digital_APIGetDishMachineOverallPerformanceForAllCDMSiteLocations()
        {
            string[] tagsOfScenario = new string[] {
                    "DishMachineOverallPerformanceForAllLocation",
                    "Integrationtest",
                    "Simaira.DigitalIntegrationtest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Simaira.Digital_API Get Dish Machine Overall Performance For All CDMSite Location" +
                    "s", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
this.FeatureBackground();
#line hidden
#line 30
 testRunner.Given("Dish Machine Overall Performance Request Payload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
 testRunner.Then("Get Dish Machine Overall Performance for Pulse Check \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
